server:
 port: 8081
 address: localhost
 
spring:
  application:
    name: SmartPay
#  profiles:
#      active: test
#  config:
#    import: optional:CONFIGURATION-SERVER:${configuration.url}    
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    name: SmartPay
    password: root
    platform: mysql
    url: jdbc:mysql://localhost:3306/smartpay?createDatabaseIfNotExist=false&autoReconnect=true&useSSL=false
    username: root
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 500KB
      max-file-size: 10MB
      max-request-size: 10MB
      resolve-lazily: false  
app:
  api:
    swagger:
      enable: true
  message: This is properties configuration for ${spring.application.name} from PRIMARY environment 
  jwt:
    secret:
      key: afafasfafafasfasfasfafacasdasfasxASFACASDFACASDFASFASFDAFASFASDAADSCSDFADCVSGCFVADXCcadwavfsfarvf 
    token:
      validity: 600000
  refresh:
      token:
        validity: 12000000    
        
file:
  upload-dir: E:/SMART-PAY-PROJECT/Document 
